apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-deploy
  labels:
    app: health-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
      - name: health-container
        image: alok04889/health-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: health-np-service
  labels:
    app: health-app
spec:
  selector:
    app: health-app

  type: NodePort
  ports:
  - nodePort: 31034  
    port: 8082
    targetPort: 8082
